.gitignore
packages/frontend/src/config.ts
packages/relay/src/config.ts

To fix .gitignore will ignore all config.ts, and add back
* packages/frontend/src/config.ts
* packages/relay/src/config.ts
Modify 
```
config.ts
```
to 
```
/config.ts
```
* packages/frontend/src/config.ts
* packages/relay/src/config.ts
```
yarn build
yarn contracts hardhat node
yarn contracts deploy
yarn relay start
yarn frontend start
```
none
none.
1. add ```packages/frontend/src/config.ts``` and ```packages/relay/src/config.ts```
2. git can't add those file because gitingnore will ignore it  
None
-   [x] Can add ```packages/frontend/src/config.ts``` and ```packages/relay/src/config.ts``` to git 
-   [x] frontend and relay can success run

fix: gitignore will ignore frontend & relay's config.ts

---

packages/relay/src/config.ts
packages/relay/src/routes/post.ts

Moved the `LOAD_POST_COUNT` constant from `packages/relay/src/routes/post.ts` to `packages/relay/src/config.ts` to centralize configuration settings. 
fix #94
To ensure better maintainability and cleaner separation of configuration values, the `LOAD_POST_COUNT` constant has been relocated to the `config.ts` file.
- `packages/relay/src/routes/post.ts`
- `packages/relay/src/config.ts`
No new tests added as this is a configuration change. Existing tests should validate the constant's new location.
Any code that imports `LOAD_POST_COUNT` from its old location will need to be updated. As of this PR, such imports have …

[Fix] #94 fix LOAD_POST_COUNT store in config.ts

---

packages/relay/src/synchornizer.ts
packages/relay/test/login.test.ts
packages/relay/test/post.test.ts
packages/relay/test/utils/UserStateFactory.ts

Fix the randomly test failed issue
#119 
add await before create method
signup test
signup test

[Test] Add synchronizer in UserStateFactory to avoid randomly failed

---

packages/relay/src/config.ts
packages/relay/src/index.ts
packages/relay/src/synchornizer.ts

Add postgresql connector for production / stage env
#140
1. Add postgres connector 
2. Implement reset mechanism for furture re-deploy contract
Store DB 
Store into DB result (Postgres instance)
After reset, the query data will be clean 
All storage 
None
1. create db instance in https://api.elephantsql.com/ 
2. Copy URL and add DB_PATH into .env
3. Test Sign up or Post successfully and check DB data
1. Re-deploy the contract
2. Set RESET_DATABASE true 
3. restart the relayer 
4. Test Sign up or Post successfully and check DB data
-   [x] Implement `resetDatabase` in Synchronizer
-   [x] Implement `PostgreSQL` …

[relay] Add postgres connector and reset method

---

packages/contracts/abi/UnirepApp.json
packages/contracts/contracts/UnirepApp.sol
packages/contracts/scripts/utils.ts
packages/contracts/test/Comment.test.ts
packages/contracts/test/SignupAndPost.test.ts
packages/contracts/test/types.ts
packages/contracts/test/utils.ts
packages/relay/src/config.ts

This PR mainly focus on the comment feature in our smart contract. There would be 2 main functions: `leaveComment` and `editComment`.
close #110 close #126 close #139 close #164 
There are two main function in comment feature:
1. `leaveComment`: 
* should verify a `epochKey` from the server. 
* should emit a Event 
```solidity
Comment(
uint256 indexed epochKey,
uint256 indexed postId,
uint256 indexed commentId,
uint256 epoch,
string content
);
```
2. `editComment`:  
* should verify a `epochLiteKey` to check the identity
* should have a input `isRemove` to emit different Event
* **EDIT**: should emit an event
```solidity
UpdatedComment(
uint256 indexed epochKey,
uint256 indexed postId,
uint256 indexed commentId,
uint256 epoch,
string newContent
);
```
* **REMOVE**: should emit an event …

[feature] [comment] [contract] comment feature in contract

---

packages/relay/src/services/VoteService.ts
packages/relay/src/singletons/schema.ts
packages/relay/test/myAccount.test.ts

Join post when fetching my account page votes
#198 
Modify the schema definition to fetch to related table entry. Specifically, add the following object to the definition of `Vote`
```
{
name: 'post',
type: 'Object',
relation: {
localField: 'postId',
foreignField: '_id',
foreignTable: 'Post',
}
}
```
Using `include` to join select post when fetching vote:
```
include: {
post: true,
}
```
- API: `/api/my-account/votes`
Unit test in `myAccount.test.ts`
N/A
N/A
N/A
-   [x] Join post when fetching my account page votes
-   [ ] All new and existing tests pass
-   [ ] I have updated the documentation (if applicable)
-   [ …

[Backend][myAccount] Join post when fetching my account page votes

---

packages/relay/src/services/PostService.ts

A quick fix on the relay test failed issue, related to the fetch postId.

[Fix] postId field in PostService query

---

packages/relay/src/routes/comment.ts
packages/relay/src/services/CommentService.ts
packages/relay/test/comment.test.ts

Update `deleteComment` function and the test for it.
#258 
#274
1. Rename a case to "delete the comment failed with wrong proof"
2. Add a case named "delete the comment failed with wrong epoch key"
3. Rename some variables in the test so that it is more accurate.
Evis add
1. Consider `postId` when delete comment
relay
relay

[Relay][Comment] add a new case for comment deletion with wrong epoch key

---

packages/frontend/src/hooks/useFetchComment.ts
packages/frontend/src/hooks/useVotes.ts

This PR updates the error handling in the useVotes function to provide more detailed information when a vote fails. Previously, the error message included only the response status; it now includes the full JSON response from the server.
fix #260 
The change was made in the useVotes function, specifically in the error handling block of the create method. The error message now awaits and includes the full JSON response from the server, which should provide more context on why a vote operation failed.
Modified file: `packages/frontend/src/hooks/useVotes.ts`
No new tests were added. The existing unit tests were run to ensure that the change did not break existing functionality. Additional tests to cover the new error message format would be beneficial.
The change is confined to error handling …

[Fix]: fix throw error just return status change to return json object

---

packages/frontend/src/hooks/useVotes.ts

- Update the key of the frontend vote API request.
close [#276](https://github.com/social-tw/social-tw-website/issues/276)
1. Login.
2. Create a post.
3. Click the vote button.
4. The vote count should be plus 1.

[Fix] key of the vote api request is wrong

---

packages/frontend/src/pages/Profile/History/DTO/Comment.ts
packages/frontend/src/pages/Profile/History/DTO/Vote.ts
packages/frontend/src/pages/Profile/History/services/CommentService.ts
packages/frontend/src/pages/Profile/History/services/PostService.ts
packages/frontend/src/pages/Profile/History/services/VoteService.ts
packages/frontend/src/types/api.ts

- Update frontend API parser for getting myProfile posts and comments.
- Update frontend Comment DTO.
fix https://github.com/social-tw/social-tw-website/issues/286
No.
- My Profile History Page.
No.
- My
No.
1. signup
2. publish post
3. leave comment
4. wait for epoch transition and check the history on the profile page
5. click the link button, the page should be redirected to /posts/${postId} or /posts/${postId}#${commentId}
No.

fix(frontend): incorrect profile history link of post and comment

---

README.md
packages/relay/src/routes/comment.ts
packages/relay/src/routes/counter.ts
packages/relay/src/routes/myAccount.ts
packages/relay/src/routes/post.ts
packages/relay/src/routes/vote.ts
packages/relay/src/services/CommentService.ts
packages/relay/src/services/singletons/TransactionManager.ts
packages/relay/src/types/InternalError.ts
packages/relay/test/comment.test.ts
packages/relay/test/counter.test.ts
packages/relay/test/post.test.ts
packages/relay/test/vote.test.ts

Move errors in relayers into `InternalError.ts` for better coding style.
close #333 

[Relay] Refactor: Move errors to InternalError.ts

---

packages/relay/src/routes/comment.ts
packages/relay/src/services/CommentService.ts
packages/relay/test/comment.test.ts

remove epoch key query parameter from fetch comments api.
close #298 

[Backend] Fix: modify fetch comment logic

---

packages/relay/src/routes/post.ts
packages/relay/src/routes/signup.ts
packages/relay/src/services/CommentService.ts
packages/relay/src/services/PostService.ts
packages/relay/src/services/UserService.ts
packages/relay/src/services/VoteService.ts
packages/relay/src/services/singletons/ActionCountManager.ts
packages/relay/src/services/singletons/TransactionManager.ts
packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts
packages/relay/src/types/Post.ts
packages/relay/test/counter.test.ts
packages/relay/test/login.test.ts
packages/relay/test/myAccount.test.ts
packages/relay/test/post.test.ts
packages/relay/test/synchornizer.test.ts
packages/relay/test/utils/signUp.ts

- Use queue to send all transactions to improve user experience.
- Move action count related operations to synchronizer. (except for vote)
closes #254 #263 
1. Save all data into db in relay first. if the data should be updated after on-chain, write all logic in synchronizer.
2. In relay, all transactions will be queued to enhance the user experience.
3. addActionCount will use DB instance instead of TransactionDB, since the data may not be flushed immediately which will cause errors.
4. add a test on post to make sure all posts from relay are on-chain
execute `yarn relay test`

[Relay] Test: move db related operations into relayer

---

packages/frontend/src/__tests__/hooks/useCreateComment.test.tsx
packages/frontend/src/__tests__/hooks/useRemoveComment.test.tsx
packages/frontend/src/contexts/User.tsx
packages/frontend/src/hooks/useCreateComment.ts
packages/frontend/src/hooks/useRemoveComment.ts
packages/relay/src/routes/comment.ts
packages/relay/src/routes/counter.ts
packages/relay/src/routes/post.ts
packages/relay/src/routes/request.ts
packages/relay/src/routes/signup.ts
packages/relay/src/routes/transition.ts
packages/relay/src/routes/user.ts
packages/relay/src/services/CommentService.ts
packages/relay/test/comment.test.ts
packages/relay/test/counter.test.ts
packages/relay/test/login.test.ts
packages/relay/test/post.test.ts
packages/relay/test/synchornizer.test.ts
packages/relay/test/vote.test.ts

This pull request aims to improve the consistency of relay returns either by being consistent with txHash or remove the unused return names.
close #303 
- relay/src/routes/*
- relay/test/*
- frontend/src/hooks/*
- frontend/src/contexts/*
- frontend/src/__tests__/hooks/*
There may be missing parts in the frontend that requires changes to apply for the relay return changes
```
yarn relay test
```
```
yarn frontend test
```

[Relay] refactor: improve consistency in relay return

---

packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts

Hot fix to use upsert in relay signup synchronizer

fix: change to upsert instead of update in relay signup synchronizer

---

packages/frontend/src/features/post/hooks/useVotes/useVotes.ts
packages/frontend/src/utils/api.ts
packages/relay/src/routes/voteRoute.ts
packages/relay/src/services/VoteService.ts
packages/relay/src/services/utils/ProofHelper.ts
packages/relay/test/vote.test.ts

feat: getAndVerifyEpochKeyLiteProof modify to not check epoch consistency, for not on-chain transaction
feat: remove vote action's enableEpochValidation for new getAndVerifyEpochKeyLiteProof changes
None
Vote api and any use getAndVerifyEpochKeyLiteProof

[Frontend][Relayer] Modify getAndVerifyEpochKeyLiteProof don't check epoch consistency

---

packages/relay/src/db/schema.ts
packages/relay/src/routes/commentRoute.ts
packages/relay/src/routes/postRoute.ts
packages/relay/src/routes/reportRoute.ts
packages/relay/src/routes/voteRoute.ts
packages/relay/src/services/CommentService.ts
packages/relay/src/services/PostService.ts
packages/relay/src/services/ReportService.ts
packages/relay/src/services/VoteService.ts
packages/relay/src/services/utils/Validator.ts
packages/relay/src/types/Comment.ts
packages/relay/src/types/InternalError.ts
packages/relay/src/types/Post.ts
packages/relay/src/types/Report.ts
packages/relay/test/comment.test.ts
packages/relay/test/post.test.ts
packages/relay/test/report.test.ts
packages/relay/test/utils/comment.ts
packages/relay/test/utils/post.ts

The purpose of this pull request is to implement the `api/report/create` API.
close #377 
- Most of the implementation logic is in `ReportService.ts`
- `CommentService.ts` and `PostService.ts` is slightly updated for post and comment existence check.
Mostly new. `CommentService` and `PostService` is slightly updated.
- should create a report and update post status
- should fail to create a report with invalid proof
- should create a report and update comment status
- should fail to create a report on the same post / comment
- should fail to create a report with non-existent post/comment

[USD121][Relay] feat: create report api

---

packages/relay/src/config.ts
packages/relay/src/services/utils/TransactionManager.ts

Fix the transaction is stuck issue.
close #412 
Referring to Optimism [Troubleshooting](fluctuation), this is a bug from their protocol design, and will be fixed in Q4. For now, we should set maxFeePerGas to at least 0.1 gwei manually.

[Bug][Relay]set up max fee per gas

---

packages/relay/src/routes/reportRoute.ts
packages/relay/src/services/ReportService.ts
packages/relay/src/types/Report.ts
packages/relay/test/report.test.ts

Add report category api `/api/report/category`
close #418 
For client side to fetch all report categories
should fetch all report categories

[UST-192][Relay] add report category api

---

packages/relay/src/routes/reportRoute.ts
packages/relay/src/services/ReportService.ts
packages/relay/test/report.test.ts

when client side fetches reports, the reported object(post / comment) should be included in the report as well, so that the user is able to read the reported object before making the adjudication.
#407 
- should fetch report whose reportEpoch is equal to currentEpoch - 1
under this test, when fetching voting reports, all reported object should be existed as well.
-   [ ] Need to add a middleware for authentication before calling fetchReport api.

[Relay] set object into report

---

packages/relay/src/routes/reportRoute.ts
packages/relay/test/report.test.ts
packages/relay/test/utils/genNullifier.ts

In [[Relay] set object into report](https://github.com/social-tw/social-tw-website/pull/424), there's a todo issue, this pr is to finish it.
1. modify the fetch api report to `/api/report?status=${reportStatus}&publicSignals=${publicSignals}&proof=${proof}`
In client side, the publicSignal & proof should serialize
```typescript
const publicSignals = JSON.stringify(stringifyBigInts(_publicSignals))
const proof = JSON.stringify(stringifyBigInts(_proof))
```
c.c. @Xiawpohr @DylanYang0523 
2. In report test, replace the hard coded AGREE_NULLIFIER & DISAGREE_NULLIFIER to real nullifier

[Fix][Relay] check epk proof before fetch report

---

packages/relay/src/routes/myAccountRoute.ts
packages/relay/src/services/CommentService.ts
packages/relay/src/services/PostService.ts
packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts
packages/relay/src/types/Comment.ts
packages/relay/src/types/InternalError.ts
packages/relay/src/types/Post.ts
packages/relay/test/comment.test.ts
packages/relay/test/report.test.ts

The purpose of this pull request is to refactor the fetch post and comment related APIs. To make sure the content is filtered once the post or comment is reported.
close #409 
- `packages/relay/src/services/CommentService.ts`: Major change in fetching
- `packages/relay/src/services/PostService.ts`: Major change in fetching
- `packages/relay/src/routes/myAccountRoute.ts`: minor fixes in service not binding.
- `packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts`: update comment status in sync correctly
- Minor changes elsewhere
Mostly adjusted the following scope to filter the content, and minor fixes and adjustment in other files.
- `packages/relay/src/services/CommentService.ts`
- `packages/relay/src/services/PostService.ts`
- `packages/relay/test/report.test.ts`: add …

refactor: block reported content

---

packages/contracts/contracts/UnirepApp.sol
packages/contracts/test/ClaimDailyLoginRep.test.ts
packages/relay/src/middlewares/CheckReputationMiddleware.ts

in this pr #435 , claimDailyLoginRep didn't call unirep attest function to add reputation, so this pr is to fix this issue.
#431 
Since epoch key lite proof only check the epoch key, it cannot prove the user is in state tree. in claimDailyLoginRep, I replace `epochKeyLiteProof` with `epochKeyProof` to make sure the user is within state tree.
after claim the rep, by using `userState.getData()`, we can check that user really claim the daily login reputation.

[Fix][Contract]fix claim daily login rep function

---

packages/relay/doc/checkin.md
packages/relay/src/routes/checkinRoute.ts
packages/relay/src/types/InternalError.ts
packages/relay/test/checkin.test.ts
packages/relay/test/utils/reputation.ts

The purpose of this pull request is to let the people who have negative reputation claim daily checkin reputation.
close #393 
Implement the `/api/checkin` by simply checking the reputation proof to make sure it's negative and allow people to claim.
- Should allow users with negative reputation to claim reputation
- Should not allow users with non-negative reputation to claim reputation
`yarn relay test`

[UST-142] [Relay] feat: checkin api

---

packages/contracts/abi/UnirepApp.json
packages/contracts/contracts/UnirepApp.sol
packages/contracts/contracts/verifierHelpers/VerifierHelperManager.sol
packages/contracts/scripts/utils/deployUnirepSocialTw.ts
packages/contracts/scripts/utils/deployVerifiersAndHelpers.ts
packages/contracts/test/ClaimDailyLoginRep.test.ts
packages/contracts/test/ClaimReportNegRep.test.ts
packages/contracts/test/ClaimReportPosRep.test.ts
packages/contracts/test/VHelperManager.test.ts
packages/contracts/test/utils.ts

add Ownable on UnirepApp & VerfierHelperManager and add onlyOwner modifier to 
- UnirepApp.sol::claim*
- VerifierManager.sol::verifierRegister
close #460 
- should successfully call all these funcion with correct owner
- claimPosRep
- claimNegRep
- claimDailyLoginRep
- verifierRegister
- should revert in each function while the signer is not the owner

Feat contract onlyowner check

---

packages/frontend/src/features/post/components/Comment/Comment.tsx
packages/frontend/src/features/post/components/CommentList/CommentList.tsx
packages/frontend/src/features/post/components/Post/Post.tsx
packages/frontend/src/features/post/components/PostList/PostList.tsx
packages/frontend/src/features/post/components/WelcomePostList/WelcomePostList.tsx
packages/frontend/src/features/post/hooks/useReportComment/useReportComment.test.ts
packages/frontend/src/features/post/hooks/useReportComment/useReportComment.ts
packages/frontend/src/features/post/hooks/useReportPost/useReportPost.test.ts
packages/frontend/src/features/post/hooks/useReportPost/useReportPost.ts
packages/frontend/src/features/reporting/components/AdjudicateNotification/AdjudicateNotification.tsx
packages/frontend/src/features/reporting/utils/types.ts
packages/frontend/src/routes/app/posts/[id]/page.tsx
packages/frontend/src/types/Comments/index.ts
packages/frontend/src/types/Post/index.ts

- fix `invalid epoch` error when making a report on the post or comment
-  execute userStateTransition before reporting a post or a comment
- add a mask on the reported posts
- add a mask on the reported comments
- show the content of the reported post or comment when users adjudicate it

[Fix] [Frontend] adjust report flow

---

packages/circuits/package.json
packages/circuits/src/ReportIdentityProof.ts
packages/circuits/src/index.ts
packages/contracts/package.json
packages/frontend/package.json
packages/frontend/src/features/core/index.ts
packages/frontend/src/features/core/services/ReportService/ReportService.ts
packages/frontend/src/features/core/utils/genReportIdentityProof.ts
packages/frontend/src/features/post/hooks/useReportPost/useReportPost.ts
packages/frontend/src/features/reporting/hooks/useAdjudicate/useAdjudicate.test.ts
packages/frontend/src/features/reporting/hooks/useAdjudicate/useAdjudicate.ts
packages/relay/package.json
packages/relay/src/services/ReportService.ts
packages/relay/src/services/utils/ProofHelper.ts

When adjudicating a report, users needs to generate `ReportIdentityProof` to agree or disagree the report.
- #390
- #394
- Add `ReportIdentityProof` class in the circuits package.
- Use `ReportIdentityProof` to verity the proof in the adjudication relay API.
- Generate `ReportIdentityProof` and submit it to relay server to adjudicate the reports
- Circuits package version
- Improve proof verification process in relay server
- Add proof generation logic in fronend

[UST-136] [Feature] generate report identity proof when submitting adjudication request

---

packages/relay/src/routes/reportRoute.ts
packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts
packages/relay/test/report.test.ts

client side will fetch the post with incorrect order, should update the post order after:
1. user reports for the post
2. synchronizer settles reports
#377

[Fix][Relay]update post order after report

---

packages/circuits/package.json
packages/contracts/package.json
packages/contracts/test/utils.ts
packages/frontend/package.json
packages/frontend/src/utils/schema.ts
packages/relay/package.json
packages/relay/test/checkReputation.test.ts
packages/relay/test/checkin.test.ts
packages/relay/test/comment.test.ts
packages/relay/test/counter.test.ts
packages/relay/test/login.test.ts
packages/relay/test/post.test.ts
packages/relay/test/report.test.ts
packages/relay/test/synchronizer.test.ts
packages/relay/test/utils/signup.ts
packages/relay/test/utils/userHelper.ts
packages/relay/test/vote.test.ts
yarn.lock

update unirep package version according to this
https://github.com/Unirep/Unirep/issues/585
https://github.com/Unirep/Unirep/pull/587
https://github.com/Unirep/Unirep/pull/586
frontend user's schema is renamed to `userSchema`
user state
If your changes have UI effects, consider attaching screenshots or videos to demonstrate them.
Provide a step-by-step guide for others to reproduce your results and verify your changes.
-   [ ] Draft implementation for `function`
-   [ ] Unit tests for `function`
-   [ ] All new and …

chore: update unirep version

---

packages/relay/src/types/Reputation.ts

This commit updates the names of the `ClaimHelpers` enum values for
`ReportNullifierVHelper` and `ReportNonNullifierVHelper` to
`reportNullifierProofVerifierHelper` and
`reportNonNullifierProofVerifierHelper`, respectively. The new names provide
more clarity and better describe the purpose of these helper functions.
close #496

[Relay] ISSUE-496 vote claim reputation failed

---

packages/frontend/src/features/core/components/EpochInfo/EpochInfo.tsx
packages/frontend/src/features/core/hooks/useEpoch/useEpoch.ts

Refetch epoch remaining time in every visits.
close #494 
The timer shows the wrong time when user creates a post in mobile because the epoch remaining time is cached and stale.
The epoch remaining time should be updated when user revisit the homepage.

fix: refetch epoch remaining time in every visits

---

packages/frontend/src/features/core/services/RelayApiService/RelayApiService.ts
packages/frontend/src/features/post/hooks/useCreateComment/useCreateComment.test.ts
packages/frontend/src/features/post/hooks/useCreatePost/useCreatePost.test.ts
packages/frontend/src/features/post/hooks/useReportComment/useReportComment.test.ts
packages/frontend/src/features/post/hooks/useReportPost/useReportPost.test.ts
packages/frontend/src/features/post/hooks/useVotes/useVotes.test.ts
packages/frontend/src/features/reporting/components/AdjudicateNotification/AdjudicateNotification.test.tsx
packages/frontend/src/features/reporting/hooks/useAdjudicate/useAdjudicate.test.ts
packages/frontend/src/features/reporting/hooks/useGetWaitForTransactReport/useWaitForTransactionReport.test.ts
packages/frontend/src/features/reporting/hooks/usePendingReports/usePendingReports.test.ts

When user's reputation is negative, generate a negative reputation proof, put this proof in authorization header of check-in API.
close #508

[Fix] [Frontend] Generate a negative reputation proof when checking in

---

packages/frontend/src/constants/config.ts
packages/frontend/src/features/core/components/ActionTable/ActionTable.tsx
packages/frontend/src/features/reporting/components/CheckInNotification/CheckInNotification.tsx
packages/frontend/src/features/reporting/components/DiscardCheckIn/DiscardCheckIn.tsx
packages/frontend/src/features/reporting/hooks/useAdjudicate/useAdjudicate.ts
packages/frontend/src/features/reporting/hooks/useCheckIn/useCheckIn.ts
packages/frontend/src/features/reporting/hooks/useNotifyCheckIn/useNotifyCheckIn.ts
packages/frontend/src/routes/app/layout.tsx
packages/relay/src/db/schema.ts
packages/relay/src/routes/checkinRoute.ts
packages/relay/src/services/ReputationService.ts
packages/relay/src/types/Reputation.ts

- Hide notification after user checks in successfully.
- Check user reputation every day.
- Show the reputation history of checking in.
close #516

[Fix] [Frontend] [Relay] Improve check in flow

---

packages/circuits/package.json
packages/contracts/package.json
packages/contracts/test/utils.ts
packages/frontend/package.json
packages/frontend/src/utils/schema.ts
packages/relay/package.json
yarn.lock

State tree leaf id is fixed, there should not be duplicated leaf in indexed db
Fix `InvalidHistoryTreeRoot` and `InvalidStateTreeRoot`
If your PR addresses a particular issue, provide its link here.
Mention all types of tests (unit, integration, performance, etc.) that you've carried out and if any specific environment or configuration is needed to run them.
Describe any existing features that might be affected by this change, or any potential backward compatibility issues, if any.
If your changes have UI …

fix: fix unirep version (2.1.5-alpha-1)

---

packages/frontend/src/features/post/components/Comment/CommentReportDialog.tsx
packages/frontend/src/features/post/components/CreatePost/CreatePost.tsx
packages/frontend/src/features/post/components/Post/PostReportDialog.tsx
packages/frontend/src/features/post/components/Post/tests/PostReportDialog.test.tsx
packages/frontend/src/features/post/components/ReportForm/ReportFormSubmitting.tsx
packages/frontend/src/features/post/hooks/useReportPost/useReportPost.ts
packages/frontend/src/features/shared/components/Backdrop/Backdrop.tsx
packages/frontend/src/features/shared/hooks/useDialog.ts

修改 report flow 與更新相關組件
close https://github.com/social-tw/social-tw-website/issues/554
- Remove the reporting success dialog
- Remove the reporting failure dialog
- 在載入對話框上新增關閉按鈕
- 顯示載入對話框 5 秒並自動關閉對話框

[Frontend] The loading state only last for 5 seconds when reporting

---

packages/relay/src/services/ReportService.ts
packages/relay/test/report.test.ts
packages/relay/test/reputation.test.ts

The purpose of this PR is to fix the implementation of settling failed report.
closes #525 
In the previous implementation, we update the report status to waitForTx while receiving the last vote. And causing the UnirepSocialSynchronizer not updating the report correctly. In order to fix the issue, we keep all the voting report update action in the UnirepSocialSynchronizer. And avoid returning report, in voting phase, through the fetchReport API.
- packages/relay/src/services/ReportService.ts
Adjust the `should fetch report whose adjudication result is tie` test to `should not fetch report whose adjudication count has reached threshold`, making sure that while the status of the report is Voting and the voting counts have reached the threshold, the fetchReport API won't return the report. …

[Backend][UST-247] fix: display failed report content

---

packages/frontend/src/features/post/components/ReportedMask/ActionLinks.tsx

Expand the community governance section in the about page when clicking '為什麼會有內容檢舉？' link
close #609

[Frontend] Expand the community governance section in the about page

---

packages/relay/src/services/PostService.ts
packages/relay/test/report.test.ts

This pull request aims to solve the issue where result of searching post would return reported content.
The expected behavior of the result of searching post would be without the reported ones. In this pull request we filter out the reported one in the fetchPosts API, whenever keyword is passed in we filtered out the reported post in the returns.
- Fetch Post related tests
- Added a check in the repost test

[UST-273][Backend] fix: filter reported content search

---

packages/contracts/contracts/UnirepApp.sol
packages/contracts/contracts/interfaces/IVerifierHelper.sol
packages/contracts/contracts/verifierHelpers/DailyClaimVHelper.sol
packages/contracts/contracts/verifierHelpers/ReportNonNullifierVHelper.sol
packages/contracts/contracts/verifierHelpers/ReportNullifierVHelper.sol
packages/contracts/contracts/verifierHelpers/VerifierHelperManager.sol
packages/contracts/scripts/utils/deployUnirepSocialTw.ts
packages/contracts/test/ClaimDailyLoginRep.test.ts
packages/contracts/test/Comment.test.ts
packages/contracts/test/SignupAndPost.test.ts
packages/contracts/test/VHelpers.test.ts
packages/contracts/test/Verifiers.test.ts
packages/contracts/test/utils.ts
packages/relay/test/checkReputation.test.ts

The purpose of this pull request is to remove the epochKeyProof in the contract and replace them with reputation proof.
- Replace epochKey proof in UnirepApp contract with reputation proof
- Add reputation proof generation helper
- Adjust tests: claim check in, post, and comment
UnirepApp contract + test across claim check in, post, and comment.
`yarn contracts test`

[UST-312][Contract] refactor: remove epkhelper contract

---

packages/frontend/src/assets/css/main.css
packages/frontend/src/constants/queryKeys.ts
packages/frontend/src/routes/app/reports/[id]/page.tsx
packages/frontend/src/routes/router.tsx

- Refactor the report details page.
- Display the pending dialog in the beginning.
- Display the failure dialog to inform user to login/signup.
close #630

feat: add pending ui on the report details page

---

packages/frontend/src/features/core/services/ReportService/ReportService.ts
packages/frontend/src/features/core/stores/actions.ts
packages/frontend/src/features/post/hooks/useReportComment/useReportComment.ts
packages/frontend/src/types/Report/index.ts
packages/frontend/src/utils/api.ts
packages/relay/src/db/schema.ts
packages/relay/src/services/ReportService.ts
packages/relay/src/types/InternalError.ts
packages/relay/src/types/Report.ts
packages/relay/test/report.test.ts
packages/relay/test/reputation_claim.test.ts

This pull request aims to solve the incorrect content display of comment report in adjudicate form by introducing several changes to the report service and related components, primarily adding support for handling `postId` in various contexts and ensuring proper validation. The changes also include updates to tests to reflect these modifications.
* [`packages/frontend/src/features/core/services/ReportService/ReportService.ts`]: Added `postId` as an optional parameter in the `createReport` method and ensured it is included in the report data.
* [`packages/frontend/src/features/core/stores/actions.ts`]: Updated `ReportCommentData` interface to include `postId`.
* [`packages/frontend/src/features/post/hooks/useReportComment/useReportComment.ts`]: Adjusted `useReportComment` hook to handle …

fix: comment report content mismatch
