.gitignore
packages/relay/src/routes/post.ts

This pull request aims to implement the relayer API for posting.
With the current code base, we could test the API with an API platform like Postman. The following image is an example.
Here are the parameters for testing:
```
{
"content": "12312",
"publicSignals": [
"1038448373275420142607644055009889520416046183430608674450639538063542650520",
"14112677913706877416423252136435525552770195945521740600904565571010154160365",
"4451353010164519564206090957593902219217783864052023977979736464899072",
"0"
],
"proof": [
"3669577489535389830316079860196206635357458271044871630758118833749938223184",
"17012046093143868869739244005179272667346372724364068586471384951096336924667",
"18544402024408249111864154949454028530663203936011362167888761652312554553527", …
```

feature/post-backend: build relayer 

---

packages/frontend/package.json
packages/frontend/src/components/shared/TwitterLoginButton.tsx
packages/frontend/src/contexts/Loading.tsx
packages/frontend/src/contexts/ToasterContext.tsx
packages/frontend/src/contexts/User.ts
packages/frontend/src/index.tsx
packages/frontend/src/layout/Navbar.tsx
packages/frontend/src/pages/Home.tsx
packages/relay/src/routes/signup.ts
yarn.lock

Add toaster to user interface showing state and error messages
-   [v] All new and existing tests pass
-   [v] I have updated the documentation (if applicable)
-   [v] My changes do not introduce new security vulnerabilities

feat: add toaster to user interface showing state

---

packages/contracts/contracts/UnirepApp.sol
packages/relay/src/config.ts
packages/relay/src/index.ts
packages/relay/src/middleware.ts
packages/relay/src/routes/post.ts
packages/relay/src/singletons/schema.ts
packages/relay/src/synchornizer.ts

In this pull request, we built the API to fetch posts from the database. Additionally, we refactored the synchronizer implementation to ensure that posts stored in the database have synchronized status with on-chain transactions.
The critical changes would be in the following files:
- packages/relay/src/synchornizer.ts
- packages/relay/src/routes/post.ts
- packages/relay/src/singletons/schema.ts
After sending a transaction, we store it in our DB. Initially, the post status is 0, indicating it was not found on-chain. Once the synchronizer locates the post on-chain, the status updates to 1.
The following image is an example of testing under local environment with Postman.
```
{
"content": "12312",
"publicSignals": [
"111149337672585511424191526241943020905354441810933815113319565006119675641 …
```

feature: fetch post endpoint

---

packages/relay/package.json
packages/relay/src/routes/post.ts
packages/relay/src/singletons/schema.ts
yarn.lock

Reverts social-tw/social-tw-website#16

Revert "Feature/post ipfs"

---

.github/workflows/CI.yml

Add CICD which includes build, test(circuits, contract, relay, frontend) and lint
https://github.com/social-tw/social-tw-website/issues
Only PR or push to main or release/integrate_0713 activates this CICD workflow.
This can be modified on the "on:" filed of the main-workflow.yml
Note that the tests of relay and frontend are not implemented yet, and that the tests of contract and the lint won't pass yet.
.github/workflows
PR that fails to build, to test, or to lint will not be abled to be merged.

[WIP] Cicd

---

packages/circuits/package.json
packages/circuits/src/DataProof.ts
packages/contracts/abi/UnirepApp.json
packages/contracts/contracts/UnirepApp.sol
packages/contracts/package.json
packages/contracts/scripts/deploy.ts
packages/contracts/test/UnirepApp.test.ts
packages/frontend/package.json
packages/frontend/src/contexts/User.ts
packages/relay/package.json
packages/relay/src/index.ts
packages/relay/src/routes/post.ts
packages/relay/src/routes/request.ts
packages/relay/src/routes/signup.ts
packages/relay/src/routes/transition.ts
packages/relay/src/routes/user.ts
packages/relay/src/synchornizer.ts
yarn.lock

Bump unirep packages to v2.0.0-beta-4 version
- circuits
- contracts
- relay
- frontend
-   [ ] Draft implementation for `function`
-   [ ] Unit tests for `function`
-   [ ] All new and existing tests pass
-   [ ] I have updated the documentation (if applicable)
-   [ ] My changes do not introduce new security vulnerabilities

feat: bump to v2.0.0-beta-4 version

---

packages/relay/src/data/User.ts
packages/relay/src/routes/signup.ts
packages/relay/src/routes/user.ts
packages/relay/src/services/UserService.ts
packages/relay/test/environment.ts
packages/relay/test/post.test.ts

closed #41 
Modularizing user related function for further testing
- loginOrInitUser
- signUp
All related testing
Post test pass

[Test][Enhancement] Modularize signup function for further testing

---

.github/workflows/main-ci.yml

Trigger CI when "push" to main
#81 
CI only.

fix: trigger ci when push to main

---

packages/frontend/src/components/login/AuthForm.tsx
packages/frontend/src/hooks/useSignupWithServer.ts
packages/frontend/src/pages/Login.tsx

Update login ui
https://github.com/social-tw/social-tw-website/issues/74
packages/frontend/src/components/login/AuthForm.tsx
packages/frontend/src/hooks/useSignupWithServer.ts
packages/frontend/src/pages/Login.tsx
View the vedios on the discord

Update login ui

---

README.md

Update the circom installation commands in readme. We just show people where to find the guide.
#69 
README.md

fix: circom installaion

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Update the pull request template and add the updated contribution guideline to it.

doc: update contribution guideline

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Introduced an enhanced README for the unirep social taiwan project to provide better project understanding and quick start guide.
#68 
The README has been overhauled to:
Display a centered logo and project title.
Showcase badges, which includes project information, linting and coding standards, GitHub actions status, and contributors count.
Present a clear project description emphasizing anonymity and secure discussions.
Offer a straightforward quickstart guide detailing installation, daemon start, and frontend/backend operations.
README.md
No tests required since this is documentation enhancement.
No impacts on existing features. Only improves the project's documentation for better user onboarding.
Please refer to the README.md on this PR's branch to view the complete visual enhancement. …

issue-68: update readme

---

packages/frontend/scripts/deploy-contracts.mjs
packages/relay/src/config.ts
packages/relay/src/routes/post.ts
packages/relay/src/routes/request.ts
packages/relay/src/singletons/TransactionManager.ts

Updated the import path of `UnirepApp.json` in `post.ts` to point to the correct ABI location.
fix #99
Changed the import path from `@unirep-app/contracts/artifacts/contracts/UnirepApp.sol/UnirepApp.json` to `@unirep-app/contracts/abi/UnirepApp.json` based on the suggestion in the linked issue.
- `social-tw-website/packages/relay/src/routes/post.ts`
Existing tests should validate the updated import. No new tests have been added as this is a configuration change.
Any functionality relying on the imported `UnirepApp.json` might be affected if the new location doesn't provide the expected contents. However, since this …

[Fix] #99 update UnirepApp ABI import path

---

packages/relay/package.json
packages/relay/src/config.ts
packages/relay/src/routes/counter.ts
packages/relay/src/routes/epochkeyaction.ts
packages/relay/src/routes/post.ts
packages/relay/src/singletons/schema.ts
packages/relay/src/synchornizer.ts
packages/relay/src/types/ActionType.ts
packages/relay/src/utils/TransactionHelper.ts
packages/relay/test/counter.test.ts
packages/relay/test/post.test.ts
packages/relay/test/utils/genProof.ts
packages/relay/test/utils/post.ts
packages/relay/test/utils/signUp.ts
yarn.lock

Add `api/counter` to fetch the number of actions(vote, post, comment...) the user made in the current epoch
close #131
`packages/relay/package.json`
`packages/relay/post.ts`
- the counter will add 1 after the user posted
- the error will occur if request doesn't contain 3 epoch keys
- the data of `EpochKeyAction` table will be deleted after the epoch ended
When members are developing action-related function like `vote` and `comment`,
make sure you also handle the `EpochKeyAction` table.
-   [ ] Add vote scenario into unit test 
-   [ ] Add comment scenario into unit test 
- …

[feature] add epochkeyaction schema and api

---

packages/frontend/package.json
packages/frontend/src/components/post/Avatar.tsx
packages/frontend/src/components/post/Comment.tsx
packages/frontend/src/components/post/Post.tsx
packages/frontend/src/layouts/AppLayout.tsx
packages/frontend/src/pages/PostDetail.tsx
packages/frontend/src/types/index.ts
packages/frontend/src/utils/formatDate.ts
yarn.lock

Add comment list
[#143](https://github.com/social-tw/social-tw-website/issues/143)
-   [x] comment list

[feature] [comment] [frontend] add comment list

---

packages/frontend/src/components/Dialog.tsx
packages/frontend/src/components/comment/Comment.tsx
packages/frontend/src/components/comment/CommentDeleteDialog.tsx
packages/frontend/src/pages/PostCreate.tsx
packages/frontend/src/pages/PostDetail.tsx

Create user interface for users to delete their comments
[#157](https://github.com/social-tw/social-tw-website/issues/157)

[feature] [comment] [frontend] delete comment UI

---

packages/frontend/package.json
packages/frontend/src/index.tsx
packages/frontend/src/socket.ts
packages/relay/package.json
packages/relay/src/index.ts
yarn.lock

Implement socket.io for real time posting and commenting
https://github.com/social-tw/social-tw-website/issues/151
Mention all types of tests (unit, integration, performance, etc.) that you've carried out and if any specific environment or configuration is needed to run them.
Describe any existing features that might be affected by this change, or any potential backward compatibility issues, if any.
If your changes have UI effects, consider attaching screenshots or videos to demonstrate them.
Provide a …

[Feature] socket io implement

---

packages/relay/src/index.ts
packages/relay/src/singletons/SocketManager.ts
packages/relay/src/types/SocketTypes.ts

Refactor SocketIO usage to singleton pattern in SocketManager class.
Closes #151 
- Extract SocketIO server creation to SocketManager class
- Make SocketManager a singleton to avoid duplicate IO instances
- Provide method to emit events through singleton instance
- packages/relay/src/index.ts
- packages/relay/src/singletons/SocketManager.ts
- packages/relay/src/types/SocketTypes.ts
- Manually tested SocketIO connection and event emitting to ensure no regression
- Change only affects SocketIO usage, no impact on existing features
1. Start relay server and client
2. Verify SocketIO connection is established
3. Emit …

[refactor] Refactor socketio to singleton

---

packages/relay/src/index.ts

This pull request resolves a CORS issue that prevented the frontend from accessing certain static resources from the server. By reordering the middleware sequence, the CORS headers are now correctly applied to all responses, including those for static files.
N/A
The main change involved moving the CORS middleware above the static file serving middleware in the index.ts file of the relay package. This ensures that the CORS headers are correctly set for all requests, including those for static files.
`packages/relay/src/index.ts`
Manual testing was performed to ensure that the frontend can now access the previously …

[fix] Fix CORS

---

packages/frontend/src/contexts/User.tsx
packages/frontend/src/hooks/useLoginWithServer.ts
packages/frontend/src/hooks/useLoginWithWallet.ts
packages/frontend/src/hooks/useSignupWithServer.ts
packages/frontend/src/hooks/useSignupWithWallet.ts
packages/frontend/src/utils/api.ts
packages/frontend/src/utils/createProviderByUrl.ts

Refactor UserContext > createUserState.
No.
No.
User.tsx,  useLoginWithServer.ts, useLoginWithWallet.ts, useSignupWithServer.ts, useSignupWithWallet.ts, api.ts, provider.ts
No.
No.
No.
Provide a step-by-step guide for others to reproduce your results and verify your changes.
-   [x] add api.ts  > fetchRelayConfig
-   [x] add provider.ts > createProviderByUrl 
-   [x] refactor createUserState 
-   [x] My changes do not …

[refactor] Refactor create user state frontend

---

packages/relay/src/index.ts
packages/relay/src/singletons/SocketManager.ts
packages/relay/src/synchornizer.ts
packages/relay/src/types/SocketTypes.ts
packages/relay/test/comment.test.ts
packages/relay/test/environment.ts
packages/relay/test/synchornizer.test.ts

Add websocket behavior when adding comment
#137 
1. Minor change in socket connection
2. Add comment event emit
3. Add Unit test when adding comment 
Comment / Vote 
Synchornizer / Comment tests all pass
Comment
Comment emit message example
```
{
postId: '0',
content: 'test content',
epochKey: '5560767280010227361837943064280507630212697937025874246496101159477480999347',
epoch: 0
}
```
-   [x]  Minor change in socket connection
-   [x]  Add comment event emit
-   [x]  Add Unit test when adding comment 
-   [ ] I have updated the documentation (if applicable)
-   [x] My …

[Relay][Comment] add socket behavior

---

packages/relay/package.json
packages/relay/src/index.ts
packages/relay/src/routes/vote.ts
packages/relay/src/singletons/SocketManager.ts
packages/relay/src/types/SocketTypes.ts
packages/relay/test/environment.ts
packages/relay/test/vote.test.ts

Implement socket io in relay server to emit vote events to clients.
close #171 
- Emit vote created/updated events with vote data
- Frontend subscribes and updates UI accordingly
- packages/relay/src/routes/vote.ts - Emit events
- packages/relay/src/singletons/SocketManager.ts - Socket io server
- packages/relay/src/types/SocketTypes.ts - Events types
- packages/relay/test/* - Added tests
- Added integration test using socket io client to validate events
- Simulates client side socket interactions
- Real-time vote updates for better UX
1. Start relay server
2. Subscribe to vote events on frontend
3. Create vote …

[feature][relay] relay add stocketio for vote action

---

packages/relay/src/routes/myAccount.ts
packages/relay/src/services/CommentService.ts
packages/relay/src/services/PostService.ts
packages/relay/src/services/VoteService.ts
packages/relay/test/myAccount.test.ts

Implement backend APIs for my account page
#198 
1. Refactor PostService and CommentService, remove epks in fetchPosts and fetchComments
2. Implement myaccount.ts to new APIs
3. Implement `fetchMyAccountPosts`, `fetchMyAccountComments`, `fetchMyAccountVotes`
4. Query parameters for new APIs includes:
- epks: `_` separated string of epoch keys, e.g. `key1_key2_key3`
- sortKey: `publishedAt` | `voteSum`
- direction: `asc` | `desc`
Remove `epks` for the following APIs
- /api/post
- /api/comment
Mention all types of tests (unit, integration, performance, etc.) that you've carried out and if any specific environment or …

[Backend][myAccount] Implement backend APIs for my account page

---

README.md

Fix readme instructions
If your PR addresses a particular issue, provide its link here.
1. ~`.env_example`~ `.env.example`
2. deploy script will overwrite the `.env`, so it can be created before deployment
Mention all types of tests (unit, integration, performance, etc.) that you've carried out and if any specific environment or configuration is needed to run them.
Describe any existing features that might be affected by this change, or any potential backward compatibility issues, if any.
If your changes have UI effects, consider attaching screenshots or videos to …

[documentation] fix: fix readme instruction

---

packages/contracts/contracts/UnirepApp.sol
packages/contracts/test/Comment.test.ts
packages/contracts/test/SignupAndPost.test.ts

The changes mainly focus on the minor contract issue and fixed comment test in contract.
There's no issue since we thought it was really minor.
- a epoch checking in Contract had been modified
- partial contract comment test had been changed
no.
The tests are all in `package/contracts/test/comment.test.ts`
no.
1. `yarn install`
2. `yarn build`
3. `yarn contracts test`
-   [X] modification of contract test
-   [X] All new and existing tests pass
-   [X] I have updated the documentation (if applicable)
-   [X] My changes do not introduce new security vulnerabilities
-   [X] Run `yarn lint:fix`

Fix/contract comment test/type error

---

packages/contracts/contracts/UnirepApp.sol
packages/contracts/test/Comment.test.ts
packages/contracts/test/SignupAndPost.test.ts
packages/relay/test/comment.test.ts
packages/relay/test/post.test.ts

Delete State Tree Root Check.
close #255 
Delete State Tree Root Check in contract.
`UnirepApp.sol`
deleted test for state root check.
1. `yarn install`
2. `yarn build`
3. `yarn contracts test`
-   [X] All new and existing tests pass
-   [X] I have updated the documentation (if applicable)
-   [X] My changes do not introduce new security vulnerabilities
-   [X] Run `yarn lint:fix`

[Fix] [Contracts] delete state tree root check

---

packages/contracts/contracts/UnirepApp.sol
packages/contracts/test/Comment.test.ts
packages/contracts/test/SignupAndPost.test.ts
packages/frontend/src/pages/Profile/History/services/CommentService.ts
packages/frontend/src/pages/Profile/History/services/PostService.ts
packages/frontend/src/pages/Profile/History/services/VoteService.ts
packages/frontend/src/types/api.ts
packages/relay/test/comment.test.ts
packages/relay/test/post.test.ts

The description in Signup is currently wrong.
close #256 
no
no
related to sign up test only
no
1. `yarn install`
2. `yarn build`
3. `yarn contracts test`
-   [X] Draft implementation for `function`
-   [X] Unit tests for `function`
-   [ ] All new and existing tests pass
-   [X] I have updated the documentation (if applicable)
-   [X] My changes do not introduce new security vulnerabilities
-   [X] Run `yarn lint:fix`

[Fix] [Contract] rewrite test descriptions

---

packages/relay/src/services/VoteService.ts

Fix typo in relay `packages/relay/src/services/VoteService.ts`
closed #257

[Fix] Relay typo

---

packages/frontend/src/pages/PostCreate.tsx
packages/frontend/src/pages/PostList.tsx

This PR adds console.log(err) statements to the onSubmit functions in PostList.tsx and PostCreate.tsx for better error logging and debugging.
fix #261 
The update includes adding a console.log statement to catch and log any errors that occur during the post creation process. This will assist in identifying and debugging issues that users might encounter when trying to create a new post.
Modified file: `packages/frontend/src/pages/PostList.tsx`
Modified file: `packages/frontend/src/pages/PostCreate.tsx`
No new tests were added. The existing tests were run to ensure that the change did not break any existing functionality. These changes are primarily for debugging purposes and do not impact the core functionality.
This change should have no impact on existing features or performance. It is …

[Fix] feat: add console log when create post catch err can console log err

---

packages/frontend/src/hooks/useFetchComment.ts

Replace hardcode url with `SERVER` from config
fix #259

fix: replace hardcode url

---

packages/frontend/src/components/post/Post.tsx
packages/frontend/src/utils/formatDate.ts

原本沒有辦法正常留言，但 #244 合併之後就可以正常發布了，但還有一些小問題順便修復。
close https://github.com/social-tw/social-tw-website/issues/236
1. 修改 comment time format 的錯誤
2. 新增 cursor to comment icon

[Issue] [Forntend] Comment small bugs

---

packages/frontend/src/contexts/User.tsx
packages/frontend/src/hooks/useSignupWithServer.ts
packages/frontend/src/hooks/useSignupWithWallet.ts

解決註冊成功後，還是會 redirect 到 welcome 的錯誤。
close https://github.com/social-tw/social-tw-website/issues/289
主要的錯誤是在 signup 這個 function 裡面，原本的 provider 會因為 state 尚未更新，以至於變成 undefined，導致錯誤並且導回 welcome
packages/frontend/src/contexts/User.tsx
packages/frontend/src/hooks/useSignupWithServer.ts
packages/frontend/src/hooks/useSignupWithWallet.ts
1. 進入首頁
2. 進行註冊
3. 註冊成功後留在首頁

[Frontend] Signup Redirect Issue

---

packages/frontend/src/components/comment/DesktopCommentForm.tsx
packages/frontend/src/components/comment/MobileCommentForm.tsx
packages/frontend/src/hooks/useVotes.ts
packages/frontend/src/pages/CreatePost/index.tsx
packages/frontend/src/pages/Home/HomePostForm.tsx
packages/frontend/src/pages/PostDetail.tsx
packages/frontend/src/pages/Profile/History/errors/ErrorUnsupportedVoteType.ts
packages/frontend/src/pages/Profile/History/services/VoteService.ts
packages/frontend/src/pages/Profile/History/store/createCommentSlice.ts
packages/frontend/src/pages/Profile/History/store/createPostSlice.ts
packages/frontend/src/pages/Profile/History/store/createVoteSlice.ts
packages/frontend/src/pages/Profile/History/types.ts
packages/frontend/src/pages/Profile/History/utils.ts
packages/frontend/src/types/api.ts

- Update API interface of relay raw vote data.
- Add invoke functions for Profile > History > Posts/Comments/Votes.
- Add handlers to invoke fetch post history when a user adds a post.
- Add handlers to invoke fetch comment history when a user adds a comment.
- Add handlers to invoke fetch vote history when a user sends a vote.
fix https://github.com/social-tw/social-tw-website/issues/283
No.
- My Profile History Pages and Services (Vote, Comment, Post).
- Desktop/Mobile Comment Form.
- Hooks > useVotes.ts
- CreatePost.
- HomePostForm.
No.
No.
1. signup
2. publish post
3. wait for the add post to succeed
4. check profile > history > posts is up to date
5. leave comment
6. wait for the add comment to succeed
7. check profile > history > comments is up to date
8. add an upvote for a post
9. …

[Issue] Profile history page won't update immediately & vote icon is incorrect

---

packages/relay/src/routes/post.ts
packages/relay/src/services/PostService.ts
packages/relay/src/types/InternalError.ts
packages/relay/test/post.test.ts

Remove "query" in get post.
close #301 
`yarn relay test`

chore: remove unused param in post

---

packages/relay/src/routes/comment.ts
packages/relay/src/routes/post.ts
packages/relay/src/services/PostService.ts

Remove "status" in fetchSiglePost and related usage
close #342 

chore: remove status in fetchSiglePost

---

packages/frontend/src/utils/formatDate.ts
packages/relay/src/services/VoteService.ts

This PR addresses an issue where vote records could potentially not be found during voting operations. The changes modify how action counts are managed by ensuring all database operations related to voting are completed before updating the action count. This ensures consistency and prevents potential issues with asynchronous operation order.Describe the changes made in your pull request here.
fix #325 
The primary change involves reordering the operations in the VoteService.ts. Previously, the action count was updated inside a callback which could lead to race conditions or inconsistencies when creating or deleting vote records. Now, all database operations (create, delete, and update) are performed sequentially before the action count is updated, ensuring data integrity and consistency …

[Frontend] Fix/ust 99 fix vote relay

---

packages/frontend/src/__tests__/hooks/useCreateComment.test.tsx
packages/frontend/src/__tests__/hooks/useRemoveComment.test.tsx
packages/frontend/src/contexts/User.tsx
packages/frontend/src/hooks/useCreateComment.ts
packages/frontend/src/hooks/useRemoveComment.ts
packages/relay/src/routes/comment.ts
packages/relay/src/routes/counter.ts
packages/relay/src/routes/post.ts
packages/relay/src/routes/request.ts
packages/relay/src/routes/signup.ts
packages/relay/src/routes/transition.ts
packages/relay/src/routes/user.ts
packages/relay/src/services/CommentService.ts
packages/relay/test/comment.test.ts
packages/relay/test/counter.test.ts
packages/relay/test/login.test.ts
packages/relay/test/post.test.ts
packages/relay/test/synchornizer.test.ts
packages/relay/test/vote.test.ts

The purpose of this pull request is to add test to fetch posts to increase the coverage.
close #302 
```
yarn relay test
```

[Relay] test: improve fetch post test

---

packages/frontend/src/hooks/useCreatePost.ts

Quick fix for createPost return in frontend

[Frontend] fix: adjust return from create post

---

.github/PULL_REQUEST_TEMPLATE.md
.husky/pre-commit
package.json
yarn.lock

Add Husky Hook for yarn lint:fix
close #63 

chore: add huskyhook of lint

---

packages/frontend/src/index.tsx

[Frontend] [Bugfix] show profile page

---

packages/relay/src/routes/userRoute.ts

[Relay][Fix] Update login callback url

---

packages/frontend/package.json

Fix to deploy on the server root.

[HotFix] Deploy frontend on the server root

---

packages/frontend/src/features/post/components/PostList/PostList.tsx
packages/frontend/src/features/post/hooks/useVotes/useVotes.test.ts
packages/frontend/src/features/post/hooks/useVotes/useVotes.ts
packages/frontend/src/routes/app/posts/[id]/page.tsx
packages/frontend/src/utils/api.ts
packages/relay/src/routes/voteRoute.ts
packages/relay/src/services/VoteService.ts
packages/relay/src/services/utils/ProofHelper.ts
packages/relay/src/types/InternalError.ts
packages/relay/test/vote.test.ts

Fix vote will get error when cancel old epoch vote, and fix vote error when finish post.
`packages/frontend/src/features/post/components/PostList/PostList.tsx`
`packages/frontend/src/features/post/hooks/useVotes/useVotes.ts`
`packages/frontend/src/utils/api.ts`
`packages/relay/src/routes/voteRoute.ts`
`packages/relay/src/services/VoteService.ts`
`packages/relay/src/services/utils/ProofHelper.ts`
`packages/relay/src/types/InternalError.ts`

fix: fix vote bug

---

packages/frontend/src/features/post/components/Post/Post.tsx
packages/frontend/src/features/post/components/Post/PostFooter.tsx

- Refactor frontend component Post.
- Add PostFooter
No.
No.
- Frontend > Components > Post
No.
- Frontend > Components > Post
No.
No.
No.
No.

refactor(fe): ui post footer

---

packages/relay/src/config.ts
packages/relay/src/services/ReportService.ts
packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts
packages/relay/src/types/Comment.ts
packages/relay/src/types/Post.ts
packages/relay/src/types/Report.ts
packages/relay/test/report.test.ts

The purpose of this pull request is to implement the settle report logic in Synchronizer.
close #387 
Implement the login in handleEpochEnded, settle the report, and update object(Post/Comment) status.
- should settle report when vote > 5 and not tie
- should continue voting when vote < 5
- should continue voting when tie
`yarn relay test`

[UST125][Relay] feat: settle report

---

packages/frontend/src/features/post/components/Comment/Comment.tsx
packages/frontend/src/features/post/components/Comment/CommentReportedMask.tsx
packages/frontend/src/features/post/components/Post/Post.tsx
packages/frontend/src/features/post/components/Post/PostReportedMask.tsx

Add reported ui mask
close https://github.com/social-tw/social-tw-website/issues/432
- Impl CommentReportedMask
- Impl PostReportedMask
- Post
- Comment
No.
- Post
- Comment
- Turn isReported var to true to check the UI. 
-   [ ] Access isReported value via relay API

[Frontend] [Report] Reported Mask

---

packages/contracts/abi/UnirepApp.json
packages/contracts/contracts/UnirepApp.sol
packages/contracts/test/ClaimDailyLoginRep.test.ts
packages/contracts/test/ClaimReportPosRep.test.ts

add claim daily login function on UnirepApp.
close #431 
for users who have negative reputation to claim daily reputation until the reputation is greater than 0 to have normal access to out platform.
- should claim daily login reputation
- should revert with wrong proof
- should revert with invalid epoch

[Contract]Feat contract claim daily login

---

packages/relay/src/routes/commentRoute.ts
packages/relay/src/routes/postRoute.ts
packages/relay/src/services/CommentService.ts
packages/relay/src/services/PostService.ts
packages/relay/src/types/InternalError.ts
packages/relay/test/comment.test.ts
packages/relay/test/post.test.ts

feat: add fetch post and comment history api
close #441 
Add two APIs to fetch post and comment history by epoch range:
1. GET /api/post/postHistory
2. GET /api/comment/commentHistory
These APIs allow users to retrieve post and comment histories within a specified epoch range.
- `packages/relay/src/types/InternalError.ts`: Added new error types for invalid epoch range and no history found
- `packages/relay/src/routes/postRoute.ts`: Added new route for fetching post history
- `packages/relay/src/routes/commentRoute.ts`: Added new route for fetching comment history
- `packages/relay/src/services/CommentService.ts`: Added new method to get comment history
- `packages/relay/src/services/PostService.ts`: Added new method to get post history
- `packages/relay/test/comment.test.ts`: Added tests …

[UST-184] [Relayer] Fetch Post & CommentHistory API

---

packages/frontend/src/features/core/components/ActionNotification/ActionNotification.tsx
packages/frontend/src/features/core/components/ActionTable/ActionTable.tsx
packages/frontend/src/features/core/index.ts
packages/frontend/src/features/core/services/UserService/UserService.ts
packages/frontend/src/features/core/stores/actions.ts
packages/frontend/src/features/post/components/PostForm/PostForm.tsx
packages/frontend/src/features/reporting/components/CheckIn/CheckIn.tsx
packages/frontend/src/features/reporting/components/CheckIn/CheckInSuccess.tsx
packages/frontend/src/features/reporting/hooks/useCheckIn/useCheckIn.ts
packages/frontend/src/features/shared/components/RichTextEditor/index.tsx

Add check-in flow
close #466 
- Add `UI` :: `Check-in Form`
- Add `UI` :: `Check-in successfully message`
- Add `Proof` :: `Check-in Proof`
- Add `API` :: `PostCheckIn`
- Show `UI` :: `Check-in Form` if user click `UI` :: `Check-in notification`
- Show `UI` :: `Check-in successfully message` if checking in successfully
- Guide to go to `Page`:: `Reputation` on `UI` :: `Check-in successfully message`
- Integrate `UI` :: `Check-in Form`  & `Proof` :: `Check-in Proof` & `API` :: `PostCheckIn`
- Prepare the proof and submit the form
- Show success message if succeed to submit.
- User can go to reputation page after submitting successfully
- Show fail message if fail to submit
Break down the progress of the PR for everyone to see what else …

[UST-161] [Frontend] [Feature]add check in flow

---

packages/relay/src/services/CommentService.ts
packages/relay/src/services/PostService.ts
packages/relay/test/report.test.ts

The purpose of this pull request is to fix the current relay implementation on returning reported and disagreed post / comment.

fix: content return status

---

packages/relay/src/services/UserService.ts
packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts

The purpose of this pull request is to resolved the signup loop issue.
closed #481 
There are two problems described in #481, this pull request resolves them by upserting the right signup data in db and remove unsused status `NOT_REGISTER` while signing up.

fix: signup loop

---

packages/frontend/src/features/post/components/ActionMenu/ActionMenuBottomSlide.tsx
packages/frontend/src/features/profile/components/AccoutHistory/CommentTable.tsx
packages/frontend/src/features/profile/components/AccoutHistory/PostTable.tsx
packages/frontend/src/features/profile/components/AccoutHistory/VoteTable.tsx
packages/frontend/src/features/profile/components/ReputationHistory/ReputationHistory.tsx
packages/frontend/src/features/profile/components/SearchByDate/SearchBtn.tsx
packages/frontend/src/features/profile/components/SearchByDate/SearchByDate.tsx
packages/frontend/src/features/profile/components/SearchByDate/SetDateBtn.tsx
packages/frontend/src/features/profile/hooks/useReputationHistory/useReputationHistory.ts
packages/frontend/src/features/shared/components/DatePicker/CustomDatePicker.css
packages/frontend/src/features/shared/components/MobileBottomNav/MobileBottomNav.tsx
packages/frontend/src/features/shared/components/Table/TableBody.tsx
packages/frontend/src/routes/app/layout.tsx
packages/frontend/src/routes/app/posts/page.tsx
packages/frontend/src/routes/app/profile/layout.tsx

- Fix to put post mask below the navbar
- Fix to show nothing initially when have not searched history yet
- Fix to put space between the button in action menu
- Fix to show post block in desktop screen
close #475 
close #476 
close #477 
close #402
close #439

[Fix] [Frontend] adjust UI styles 

---

packages/frontend/package.json
packages/frontend/src/features/auth/components/ProtectedRoute/ProtectedRoute.tsx
packages/frontend/src/features/auth/components/SignupPendingTransition/SignupPendingTransition.tsx
packages/frontend/src/features/auth/hooks/useAuthStatus/useAuthStatus.ts
packages/frontend/src/features/core/hooks/useUserState/useUserState.ts
packages/frontend/src/features/shared/components/MobileBottomNav/MobileBottomNav.tsx
packages/frontend/src/features/shared/components/ResetStorage/ResetStorage.tsx
packages/frontend/src/setupTests.ts
packages/frontend/src/utils/schema.ts
yarn.lock

In the current useUserState we store db in memory, and by updating to indexdb will make it faster
close #471

[Frontend] setup IndexedDB

---

packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts
packages/relay/src/types/Report.ts
packages/relay/test/report.test.ts

Adjust the adjudicate value to be consistent with FE and design.

fix: adjudicate value inconsistent

---

packages/frontend/src/features/post/components/Comment/CommentReportDialog.tsx
packages/frontend/src/features/post/components/Post/PostReportDialog.tsx
packages/frontend/src/features/reporting/components/Adjudicate/Adjudicate.test.tsx
packages/frontend/src/features/reporting/components/Adjudicate/ReportReason.tsx

Show the correct report category in adjudication dialog
close #491

[Frontend] fix to submit report category

---

packages/relay/src/index.ts
packages/relay/src/middlewares/CheckReputationMiddleware.ts
packages/relay/src/routes/checkinRoute.ts
packages/relay/src/routes/commentRoute.ts
packages/relay/src/routes/counterRoute.ts
packages/relay/src/routes/myAccountRoute.ts
packages/relay/src/routes/postRoute.ts
packages/relay/src/routes/reportRoute.ts
packages/relay/src/routes/reportsRoute.ts
packages/relay/src/routes/reputationRoute.ts
packages/relay/src/routes/transitionRoute.ts
packages/relay/src/routes/voteRoute.ts
packages/relay/src/services/CommentService.ts
packages/relay/src/services/PostService.ts
packages/relay/src/services/ReportService.ts
packages/relay/src/services/UserService.ts
packages/relay/src/services/VoteService.ts
packages/relay/src/services/utils/ErrorHandler.ts
packages/relay/src/services/utils/ProofHelper.ts
packages/relay/src/services/utils/TransactionManager.ts
packages/relay/src/types/InternalError.ts
packages/relay/test/report.test.ts

The purpose of this pull request is to throw the error in Transaction Manager
Mainly throw the error in `TransactionManager`
Also adjust the error type in InternalErrors
Main: TransactionManager
Minor: All over relay for adjusting Error type

[Relay] fix: remove addition try catch

---

packages/circuits/package.json
packages/contracts/package.json
packages/contracts/test/utils.ts
packages/frontend/package.json
packages/frontend/src/utils/schema.ts
packages/relay/package.json
yarn.lock

Describe the changes made in your pull request here.
If your PR addresses a particular issue, provide its link here.
Mention all types of tests (unit, integration, performance, etc.) that you've carried out and if any specific environment or configuration is needed to run them.
Describe any existing features that might be affected by this change, or any potential backward compatibility issues, if any.
If your changes have UI effects, consider attaching screenshots or videos to demonstrate them.
Provide a …

fix: downgrade unirep version

---

packages/frontend/src/features/core/components/ActionNotification/ActionNotification.tsx
packages/frontend/src/features/core/stores/actions.ts

依照 ui mockup 修改文字敘述
close https://github.com/social-tw/social-tw-website/issues/532

[UST-234] [Frontend] Enhance "Transaction" Concept Explanation for Web2 Users

---

packages/frontend/src/features/core/stores/actions.ts
packages/frontend/src/features/post/components/Post/Post.tsx
packages/frontend/src/features/post/components/PostList/PostList.tsx
packages/frontend/src/routes/app/posts/[id]/page.tsx
packages/frontend/src/types/Post/index.ts
packages/frontend/src/utils/helpers/postMaskHelper.ts

如果是用戶發布的貼文，被檢舉後不用顯示遮罩。
close https://github.com/social-tw/social-tw-website/issues/548
新增 isMyEpochKey 的 filter 去判斷是否為用戶發布的貼文
1. 建立兩個帳號
2. 其中一個帳號建立貼文，另外一個帳號檢舉
3. 發布者看的到貼文，而其他人只能看到遮罩

[Frontend] [Feat]: Display reported or blocked content for owner

---

packages/frontend/src/features/post/components/PostList/PostList.tsx
packages/frontend/src/routes/app/posts/[id]/page.tsx

用戶點擊主頁中的評論圖示按鈕時，立即轉到貼文頁面並打開評論對話框。
close https://github.com/social-tw/social-tw-website/issues/553
利用 route 去判斷要不要打開評論框

[Frontend] Improve the commenting process to make it more convenient and concise

---

.vscode/settings.json
packages/frontend/src/constants/queryKeys.ts
packages/frontend/src/features/core/components/ActionNotification/ActionNotification.tsx
packages/frontend/src/features/core/hooks/useRequestData/useRequestData.ts
packages/frontend/src/features/core/stores/actions.ts
packages/frontend/src/features/post/components/PostList/PostList.tsx
packages/frontend/src/features/post/hooks/useVotes/useVotes.ts
packages/frontend/src/routes/app/posts/[id]/page.tsx
packages/frontend/src/types/Vote/index.ts

使用者投票時新增進度條
close https://github.com/social-tw/social-tw-website/issues/550
更新 action store 新增 voting 相關的動作，並且更新顯示文字以及 ui

[Frontend] Display progress bar under Epoch timer when user votes a post

---

packages/frontend/src/features/auth/components/LoginButton/LoginButton.tsx
packages/frontend/src/features/auth/components/TwitterButton/TwitterButton.tsx
packages/frontend/src/routes/onboarding/signup/internal/page.tsx
packages/frontend/src/routes/onboarding/signup/page.tsx
packages/frontend/src/routes/welcome/page.tsx
packages/frontend/tailwind.config.js

- Update X icon and title
- Add an explanation about X integration 
close #526

[Frontend] Enhance Documentation on X Integration and Data Usage

---

packages/frontend/src/features/auth/components/AuthNoteDialog/AuthNoteDialog.tsx
packages/frontend/src/features/auth/components/Greeting/Greeting.tsx
packages/frontend/src/routes/onboarding/login/internal/page.tsx
packages/frontend/src/routes/onboarding/signup/internal/page.tsx

- modify the explanation about server and wallet signup
- modify signup title
close #528

[Frontend] Enhance Explanation of Direct vs. Wallet Registration Options

---

packages/frontend/src/features/core/components/ActionNotification/ActionNotification.tsx
packages/frontend/src/features/core/components/ActionTable/ActionTable.test.tsx
packages/frontend/src/features/core/components/ActionTable/ActionTable.tsx

- Add a title on the action table
close #533

[Frontend] Enhance Visualization of Pending Transactions for Better User Understanding

---

packages/relay/src/index.ts
packages/relay/src/routes/postRoute.ts
packages/relay/src/routes/reportRoute.ts
packages/relay/src/services/PostService.ts
packages/relay/src/services/singletons/UnirepSocialSynchronizer.ts
packages/relay/test/post.test.ts
packages/relay/test/report.test.ts
packages/relay/test/vote.test.ts

1. Removed the post cache, ((( please review my comment in this ticket(#520), I believe the fetching post behavior will be bottleneck after removing the cache. 
2. Removed the post filter and fixed related test
3. Added keyword selection ((( this is related above fetching post behavior, add search by keyword, and it should also impact post fetching 
#520 
#544 
#546 
post/account/vote/comment, all behaviors that require post fetching are impacted.
Minor add tests for keyword selection, which should not impact current tests.
Try keyword selection, the query response should have related content
-   [x] Removed Post …

[USD-231][UST-229][UST-256] Remove the cache and post filter content and keyword selection

---

packages/frontend/src/features/auth/components/ProtectedRoute/ProtectedRoute.tsx
packages/frontend/src/routes/router.tsx
packages/frontend/src/routes/start/launch/page.tsx
packages/frontend/src/utils/helpers/epochKey.ts

- Add an about link on the launch page
close #584

[Frontend] Add button to about page

---

packages/frontend/src/features/shared/components/Inputs/SearchInput.tsx
packages/frontend/src/features/shared/components/RichTextEditor/index.tsx

解決路由切換時會自動 Focus 到 Create Post 的問題
移除 AutoFocusPlugin 以防止用戶搜尋時，自動 Focus 到 RichTextEditor 的問題

[Frontend] Fix Search Posts and Create Post Auto Focus Problem

---

packages/frontend/src/routes/app/about/page.tsx

feat(about): update never expired discord link

[Frontend][UST-294] update discord link

---

packages/frontend/src/routes/app/layout.desktop.tsx

Adjust styles of `AppLayout`
close #602 
close #603

[Frontend] Adjust desktop layout styles

---

packages/frontend/src/features/post/components/Comment/Comment.tsx
packages/frontend/src/features/post/components/CommentFormDesktop/CommentFormDesktop.tsx
packages/frontend/src/features/shared/components/RichTextEditor/index.tsx

The line break character in the comment block should be displayed
close #605

[Frontend] Display line break charactor in the comment block

---

packages/frontend/src/features/post/components/PostList/PostList.tsx

Fix the post link when clicking the comment icon in the post
close #607

[Frontend] Fix the post link when clicking the comment icon in the post

---

packages/frontend/src/routes/app/posts/[id]/page.tsx

修復發文者無法在 PostDetails 看到文章的錯誤
新增 epoch prop 到 Post component 之中，以避免空 epcoh 值導致 isMyepochKey function 出現錯誤

[Frontend] Fix PostMask Showing Bug

---

packages/frontend/src/routes/app/layout.desktop.tsx
packages/frontend/src/routes/app/layout.mobile.tsx

- Restore scroll position when navigating the previous page
close #558

[Frontend] Restore scroll position when navigating the previous page

---

packages/frontend/src/features/core/components/UITour/UITour.tsx

- Adjust the backdrop to be a little bit opaque.
- Don't scroll the page when changing the tour step
close #620

[Frontend] Adjust UI Tour styles and settings

---

packages/frontend/src/features/notification/components/NotificationItem/NotificationItem.tsx
packages/frontend/src/features/reporting/hooks/useBackgroundReputationClaim/useBackgroundReputationClaim.ts
packages/frontend/src/features/reporting/hooks/useReportAdjudicatorReputation/useReportAdjudicatorReputation.ts
packages/frontend/src/features/reporting/hooks/useReportEpochKeyReputation/useReportEpochKeyReputation.ts
packages/frontend/src/types/Report/index.ts
packages/frontend/src/types/api.ts
packages/frontend/src/utils/api.ts

- Send the notification for the result of the report that users adjudicate
close #624

[Frontend] Send notification for the result of the report that users adjudicate

---

packages/frontend/src/features/post/components/Comment/Comment.tsx
packages/frontend/src/features/post/components/Comment/CommentActionMenu.tsx
packages/frontend/src/features/post/components/Comment/CommentReportDialog.tsx
packages/frontend/src/features/post/components/PostItem/PostReportDialog.tsx
packages/frontend/src/features/reporting/components/Adjudicate/ReportContent.tsx

- Display comment content on the report dialog
close #622

[Frontend] Display comment content on the report dialog

---

packages/contracts/contracts/UnirepApp.sol

fix daily login rep  claims more than once issue.
#579

[UST-196][Contract][FIX] Check if reputation is negative and the epoch last claimed proof < 1 day

---

packages/frontend/src/features/core/services/CommentService/CommentService.ts
packages/frontend/src/features/core/services/PostService/PostService.ts
packages/frontend/src/features/core/services/ReportService/ReportService.ts
packages/frontend/src/features/core/services/UserService/UserService.ts
packages/frontend/src/features/core/services/VoteService/VoteService.ts
packages/frontend/src/features/core/utils/genDailyClaimProof.ts
packages/frontend/src/features/profile/components/ReputationHistory/ReputationHistory.tsx

Replace to the ReputationProof under the below actions:
- leave a post
- leave a comment
- vote a post
- report a post
- fetch pending reports
- check in
close #637

feat: replace epochKey proof with reputation proof
